In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/FA21 CMPE 255 Term Project/PM2.5/daily_88101_2001.csv", encoding="utf8")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

#Make sure to add a shortcut to the shared folder in your own drive before running

In [ ]:
df.head(3)

  State Code  County Code  ...                  CBSA Name  Date of Last Change
0          1            3  ...  Daphne-Fairhope-Foley, AL           2015-04-02
1          1            3  ...  Daphne-Fairhope-Foley, AL           2015-04-02
2          1            3  ...  Daphne-Fairhope-Foley, AL           2015-04-02

[3 rows x 29 columns]

PM 2.5: Need to only average for arithmetic mean and AQI

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166081 entries, 0 to 166080
Data columns (total 29 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   State Code           166081 non-null  object
 1   County Code          166081 non-null  int64
 2   Site Num             166081 non-null  int64
 3   Parameter Code       166081 non-null  int64
 4   POC                  166081 non-null  int64
 5   Latitude             166081 non-null  float64
 6   Longitude            166081 non-null  float64
 7   Datum                166081 non-null  object
 8   Parameter Name       166081 non-null  object
 9   Sample Duration      166081 non-null  object
 10  Pollutant Standard   166081 non-null  object
 11  Date Local           166081 non-null  object
 12  Units of Measure     166081 non-null  object
 13  Event Type           166081 non-null  object
 14  Observation Count    166081 non-null  int64
 15  Observation Percent  166081 non-null  float64
 16  Arithmetic Mean      166081 non-null  float64
 17  1st Max Value        166081 non-null  float64
 18  1st Max Hour         166081 non-null  int64
 19  AQI                  166081 non-null  int64
 20  Method Code          166081 non-null  int64
 21  Method Name          166081 non-null  object
 22  Local Site Name      147177 non-null  object
 23  Address              166081 non-null  object
 24  State Name           166081 non-null  object
 25  County Name          166081 non-null  object
 26  City Name            166081 non-null  object
 27  CBSA Name            159027 non-null  object
 28  Date of Last Change  166081 non-null  object
dtypes: float64(5), int64(8), object(16)
memory usage: 36.7+ MB

In [ ]:
df['Observation Count'].value_counts()

1    166081
Name: Observation Count, dtype: int64